name: release

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - metadata.json
      - .github
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v4
      - uses: geertvdc/setup-hub@master

      - name: package and releases
        run: |
          ignored="! -path $(pwd) "
          for i in $(cat .templateignore); do
              ignored+="! -name $i "
          done
          files=$(find $(pwd) -maxdepth 1 $ignored)
          mkdir typescript
          cp -r $files ./typescript
          zip -r typescript.zip ./typescript;
          openssl sha256 typescript.zip | cut -d " " -f2 > typescript.zip.sha256
          version=$(jq -r ".version" metadata.json)
          hub release create -m "v$version" "v$version"
          hub release edit -m "" -a typescript.zip "v$version"
          hub release edit -m "" -a typescript.zip.sha256 "v$version"
      - name: setup git
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - name: bump version
        run: |
          git clean -dfx
          version=$(jq -r ".version" metadata.json | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $(jq -r ".version = \"$version\"" metadata.json) | jq . > new_metadata.json
          cat new_metadata.json > metadata.json
          git add metadata.json
          git commit -m "Bumped version to $version"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" master
